package cc.ddrpa.minecraft.rowinglink.client.config;

import cc.ddrpa.minecraft.rowinglink.RowingLinkMod;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import net.fabricmc.loader.api.FabricLoader;
import org.slf4j.Logger;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;

public class RowingConfig {
    private static final Logger LOGGER = RowingLinkMod.LOGGER;
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private static final Path CONFIG_PATH = FabricLoader.getInstance()
            .getConfigDir()
            .resolve("rowinglink.json");

    public NetworkConfig network = new NetworkConfig();
    public PhysicsConfig physics = new PhysicsConfig();
    public PropulsionConfig propulsion = new PropulsionConfig();
    public SteeringConfig steering = new SteeringConfig();
    public FeedbackConfig feedback = new FeedbackConfig();
    public UsabilityConfig usability = new UsabilityConfig();

    public static RowingConfig load() {
        if (Files.exists(CONFIG_PATH)) {
            try (Reader reader = Files.newBufferedReader(CONFIG_PATH)) {
                RowingConfig config = GSON.fromJson(reader, RowingConfig.class);
                if (config != null) {
                    // Ensure new config sections exist (backwards compat)
                    if (config.propulsion == null) config.propulsion = new PropulsionConfig();
                    if (config.feedback == null) config.feedback = new FeedbackConfig();
                    if (config.usability == null) config.usability = new UsabilityConfig();
                    return config;
                }
            } catch (Exception e) {
                LOGGER.error("Failed to load config, using defaults", e);
            }
        }
        return new RowingConfig();
    }

    public void save() {
        try {
            Files.createDirectories(CONFIG_PATH.getParent());
            try (Writer writer = Files.newBufferedWriter(CONFIG_PATH)) {
                GSON.toJson(this, writer);
            }
        } catch (IOException e) {
            LOGGER.error("Failed to save config", e);
        }
    }

    public static class NetworkConfig {
        public int udpPort = 19840;
        public int connectionTimeoutMs = 5000;
    }

    public static class PhysicsConfig {
        public double maxSpeed = 0.5;
        // Per-tick horizontal velocity multiplier to counteract vanilla water drag (~0.9/tick).
        // 1.0 = vanilla drag, >1.0 = less drag. Default 1.06 → effective retention ~0.954/tick.
        public double dragCompensation = 1.06;
    }

    public static class PropulsionConfig {
        // Base paddle ticks generated by one virtual stroke.
        public double baseTicksPerStroke = 6.0;
        // Global manual scaler for matching in-game distance to machine distance.
        public double distanceScale = 1.0;
        // Power response around a reference training wattage.
        public double referencePower = 140.0;
        public double powerGamma = 1.12;
        public double minPowerFactor = 0.65;
        public double maxPowerFactor = 1.55;
        // Cadence sweet spot for game feel.
        public double targetSpm = 28.0;
        public double cadenceSigma = 6.0;
        public double minCadenceFactor = 0.80;
        public double maxCadenceFactor = 1.30;
        public double lowSpmThreshold = 12.0;
        // Smooth impulse accumulation to avoid "robotic" lockstep feel.
        public double impulseSmoothing = 0.30;
        // Optional closed-loop distance matching using machine odometer.
        public boolean autoDistanceMatch = true;
        public double distanceMatchWarmupMeters = 25.0;
        public double distanceMatchMinScale = 0.70;
        // <= 0 means no upper limit (debug/calibration mode).
        public double distanceMatchMaxScale = 1.45;
        // Safety cap against runaway pulses.
        public int maxPaddleTicksPerStroke = 18;
    }

    public static class SteeringConfig {
        public int steerLookAhead = 15;
        public int steerFanAngle = 60;
        public int steerFanRays = 9;
        public double steerMaxTurnRate = 2.0;
        public int steerCooldownTicks = 60;
        public int steerStopDistance = 3;
        public double steerOpenWaterThreshold = 0.2;
    }

    public static class FeedbackConfig {
        public boolean showHud = true;
    }

    public static class UsabilityConfig {
        public boolean autoConnect = false;
        public boolean shownWelcome = false;
    }
}
